// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAExpQVJGb99SvHkXL-1yCyMYXygHjC4D4',
    appId: '1:199189751526:web:5802a617fd642f1a0c3d27',
    messagingSenderId: '199189751526',
    projectId: 'ecommercedb-f748e',
    authDomain: 'ecommercedb-f748e.firebaseapp.com',
    storageBucket: 'ecommercedb-f748e.firebasestorage.app',
    measurementId: 'G-Z2KWXQEW75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwW_UiwNu2aKQoWzH5EuB9a8cHae2rtKE',
    appId: '1:199189751526:android:5563ae3127aba3440c3d27',
    messagingSenderId: '199189751526',
    projectId: 'ecommercedb-f748e',
    storageBucket: 'ecommercedb-f748e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLIU1lZJi-hFbDoSPQHdallMHUvuJwsSU',
    appId: '1:199189751526:ios:2919bbd0609f029d0c3d27',
    messagingSenderId: '199189751526',
    projectId: 'ecommercedb-f748e',
    storageBucket: 'ecommercedb-f748e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLIU1lZJi-hFbDoSPQHdallMHUvuJwsSU',
    appId: '1:199189751526:ios:2919bbd0609f029d0c3d27',
    messagingSenderId: '199189751526',
    projectId: 'ecommercedb-f748e',
    storageBucket: 'ecommercedb-f748e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAExpQVJGb99SvHkXL-1yCyMYXygHjC4D4',
    appId: '1:199189751526:web:51ef99a2f22de6b30c3d27',
    messagingSenderId: '199189751526',
    projectId: 'ecommercedb-f748e',
    authDomain: 'ecommercedb-f748e.firebaseapp.com',
    storageBucket: 'ecommercedb-f748e.firebasestorage.app',
    measurementId: 'G-NXLQRCB2J1',
  );

}